# Generated by Django 5.2.9 on 2026-02-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='local_body',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
